name: Deploy via SFTP (SSH Key)

on:
  push:
    branches:
      - "main"
    paths:
      - "html-version/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "html-version/*"
          target: ${{ secrets.SFTP_REMOTE_PATH }}
